import { Transaction } from "@/types/transaction";

export const realisticTransactions: Transaction[] = [
  {
    id: "tx1",
    title: "January Salary",
    amount: 280000,
    type: "income",
    category: "Salary",
    date: "2026-01-28",
  },
  {
    id: "tx2",
    title: "House Rent",
    amount: 120000,
    type: "expense",
    category: "Rent",
    date: "2026-01-02",
  },
  {
    id: "tx3",
    title: "Groceries",
    amount: 18500,
    type: "expense",
    category: "Food",
    date: "2026-01-06",
  },
  {
    id: "tx4",
    title: "Transport",
    amount: 7200,
    type: "expense",
    category: "Transport",
    date: "2026-01-08",
  },
  {
    id: "tx5",
    title: "Freelance Payment",
    amount: 95000,
    type: "income",
    category: "Freelance",
    date: "2026-01-14",
  },
  {
    id: "tx6",
    title: "Internet Subscription",
    amount: 15000,
    type: "expense",
    category: "Utilities",
    date: "2026-01-15",
  },
  {
    id: "tx7",
    title: "Electricity Bill",
    amount: 22000,
    type: "expense",
    category: "Utilities",
    date: "2026-01-18",
  },
  {
    id: "tx8",
    title: "February Salary",
    amount: 280000,
    type: "income",
    category: "Salary",
    date: "2026-02-01",
  },
  {
    id: "tx9",
    title: "Dining Out",
    amount: 12500,
    type: "expense",
    category: "Food",
    date: "2026-02-05",
  },
  {
    id: "tx10",
    title: "Ride Hailing",
    amount: 9000,
    type: "expense",
    category: "Transport",
    date: "2026-02-07",
  },
];
